### PR TITLE
📝 Minor adjustment

### PR DESCRIPTION
**Pull request by ThijmenGThN**
There seems to be a small mistake in here, let's solve that 😊

Thank you for stirring up this amazing script, couldn't have done it myself this quickly!

### CODE REVIEW

**Review by cdp1337 — APPROVED** [review]
Thanks a bunch!  (I just can never remember the name of that damned file)

**Comment by ThijmenGThN** [comment]
Whoops, noticed something else!

**Comment by cdp1337** [comment]
It's been a **LONG** weekend for me.

**Comment by ThijmenGThN** [comment]
I'm currently afk on mobile but readme states: ```sudo -u steam nano /etc/steam/island-GameUserSettings.ini```
Should be /home/, I think: ```sudo -u steam nano /home/steam/island-GameUserSettings.ini```

This is just me being picky, amazing work!

**Comment by ThijmenGThN** [comment]
> It's been a **LONG** weekend for me.

I know right! All good though, haha 😉

**Comment by cdp1337** [comment]
Hey, no worries about being picky, I prefer good criticism even if it's over nit picky things if it leads to better code and/or documentation!  Also got your other fix for /etc -> /home committed.

**Pull request merged**
